### ISSUE TITLE
move the scripts for the bot into a submodule?

### ISSUE THREAD

**Issue by Cadair** [astropy/conda-builder-affiliated#30]
Just a thought, 

I have ~~stolen~~ borrowed your code for the sunpy build repo. The scripts in `affiliated_builder` and the two `build_bdist` scripts are more general than the rest of the repo, so it would be handy for me if I could get updates for them...

If I decide to keep the builder seperate, then I might just submodule your whole repo into my builder and change the paths, but it seems a little more overkill than is needed.

Also, I just noticed there is no license in this repo...

**Comment by mwcraig** [comment]
After mulling this over for a day I'm wondering if it would make sense to separate the scripts into a separate installable package, listed as a dependency for the building. One will presumably want to keep recipes, etc, in a repo, and that repo should also contain channel information, etc.

So I'm thinking a few changes:
- Move the scripts into a separate repo.
- Move all of the configuration items (channel name, etc) from the scripts into configuration files.
- Help get a new version of obvious-ci released so that it doesn't need to be submoduled (there are a few other people using it, but I've vendored in the latest dev version because its interface is easier, I think, than the last release).

Do the first two of those, at least, seem reasonable?

**Comment by Cadair** [comment]
Installable package makes a lot of sense, it would make it easier to setup a build repo. (which might be one of the answers to the wheels discussion on astropy-dev at the moment). I do wonder though how much of the stuff in this repo would not be at home inside Obvious-CI, a lot of it seems to have the same overall goals??

Any of this is obviously dependant upon having the configs in the `travis.yml` and `appveyor.yml` files, so that might be a good start.

**Comment by mwcraig** [comment]
head over to here for the broader discussion about  building up a conda channel with lots of packages: https://groups.google.com/forum/?hl=en#!forum/conda-forge

You may have to request membership to post...and most of the actual work so far has been at https://github.com/conda-forge/conda-smithy (though the work has been very limited and conda-smithy isn't really working yet).

**Comment by mwcraig** [comment]
@Cadair -- the scripts are now in a separate repo https://github.com/astropy/conda-build-tools that is separate from the repo with the list of packages to be built, e.g. https://github.com/astropy/conda-channel-astropy

The build tools have a couple outstanding issues before they are ready for prime time (mostly fixes in the template travis/appveyor files)
