### ISSUE TITLE
Add naima?

### ISSUE THREAD

**Issue by cdeil** [astropy/conda-builder-affiliated#33]
Can / should we add Naima by @zblz to the Astropy conda channel?
https://github.com/zblz/naima

It's not an official Astropy-affiliated package, but it uses the package template and uses Astropy a lot and is overall awesome, so I hope it could be added.

The question is: does it make sense for pure-Python packages, i.e. is there any advantage over pip-installing those?

I'm currently preparing the Gammapy 0.3 release and am re-writing the install instructions: 
https://gammapy.readthedocs.org/en/latest/install.html#id1
https://github.com/gammapy/gammapy/blob/master/gammapy-conda-install.sh#L51

I think it could be useful to have all packages via conda, instead of some via pip?
E.g. automatically updating as new releases appear is easier, no?

**Comment by zblz** [comment]
re: affiliated, I was planning on requesting affiliated status in September, when people are back from vacation and there can be a bit more of eyes on the topic.

I had not considered it before since, as you mention, there is not much advantage on first installation in conda vs pip for python only packages. However, reading your `gammapy` installation instructions, I realised that having `naima` in conda would make keeping and updated astropy stack plus naima much easier. Therefore, I am definitely for including it in the conda builder, but maybe wait until naima is at least provisionally affiliated.

**Comment by mwcraig** [comment]
I don't have any objections to it -- we are already packaging non-astronomy dependencies for some affiliated packages (astroquery, and there may be others), and this seems to fall into that category regardless of its status as affiliated package.

The main advantage to having all dependencies in conda is that installation is one-line: `conda install gammapy`.

There is a mechanism in anaconda for including both conda and pip requirements (see docs for conda env) but it is lacking in a couple ways: no way to specify an anaconda channel, and it creates an environment instead of installing packages into an existing environment (like the root env).

In the longer term (1-3 months??) there will hopefully be an anaconda channel with a much broader array of packages in it.

**Comment by mwcraig** [comment]
First step to adding `naima` would be to open a PR to add it to `requirements.txt`...more often than not this exposes build problems that need to be fixed, but gets us started down that road.

**Comment by mwcraig** [comment]
PS -- @zblz, I hope you don't take my earlier comments to mean I'm in any way _opposed_ to adding `naima` as an affiliated package. I just don't think its relevant to adding it to the channel since its a dependency of `gammapy`.

**Comment by cdeil** [comment]
@mwcraig - I was hoping you say that dependencies for Astropy-affiliated packages are welcome here, i.e. that this "conda build service and help station" can be used.

I might open one more pull request for [iminuit](https://github.com/iminuit/iminuit), which is an optional dependency for Gammapy and sncosmo.
What's this Anaconda channel with a much broader array of packages in it that you mentioned.
Does it make sense to add iminuit here now or should I wait for that?

@zblz – Do you want to make a PR adding naima here, or should I attach a commit to this issue?

**Comment by mwcraig** [comment]
Closed by #34 -- naima should now be available!
